CREATE DATABASE IF NOT EXISTS ictlab_community CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ictlab_community;

CREATE TABLE IF NOT EXISTS community_users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 display_name VARCHAR(40) NOT NULL,
 session_key VARCHAR(128) NOT NULL,
 status ENUM('active','muted','banned') NOT NULL DEFAULT 'active',
 joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_session_key(session_key)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS community_agreements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 rules_version VARCHAR(20) NOT NULL,
 accepted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 ip_hash CHAR(64) NULL,
 FOREIGN KEY(user_id) REFERENCES community_users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS posts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 category VARCHAR(40) NOT NULL DEFAULT 'General',
 title VARCHAR(140) NOT NULL,
 body TEXT NOT NULL,
 resource_url VARCHAR(1000) NULL,
 status ENUM('visible','hidden','deleted') NOT NULL DEFAULT 'visible',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(category), INDEX(created_at),
 FOREIGN KEY(user_id) REFERENCES community_users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS comments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 post_id BIGINT UNSIGNED NOT NULL,
 user_id INT UNSIGNED NOT NULL,
 body TEXT NOT NULL,
 status ENUM('visible','hidden','deleted') NOT NULL DEFAULT 'visible',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES community_users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 reporter_id INT UNSIGNED NOT NULL,
 post_id BIGINT UNSIGNED NULL,
 comment_id BIGINT UNSIGNED NULL,
 reason VARCHAR(80) NOT NULL,
 details VARCHAR(500) NULL,
 status ENUM('open','reviewed','dismissed','actioned') NOT NULL DEFAULT 'open',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(reporter_id) REFERENCES community_users(id) ON DELETE CASCADE,
 FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
 FOREIGN KEY(comment_id) REFERENCES comments(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS blocked_terms (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 term VARCHAR(120) NOT NULL UNIQUE,
 category VARCHAR(50) NOT NULL DEFAULT 'inappropriate language',
 active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS moderation_actions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 admin_label VARCHAR(60) NOT NULL DEFAULT 'Owner',
 action_type VARCHAR(60) NOT NULL,
 target_type VARCHAR(30) NOT NULL,
 target_id BIGINT UNSIGNED NOT NULL,
 note VARCHAR(500) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 message VARCHAR(255) NOT NULL,
 link VARCHAR(500) NULL,
 is_read TINYINT(1) NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES community_users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT IGNORE INTO blocked_terms(term,category) VALUES
('idiot','harassment'),('stupid','harassment'),('scam link','spam/scam'),('buy followers','spam/scam');
